Add an upgrade step to update the dexterity indexer behavior name
plone/plone.app.upgrade pull request #301
Opened 2022-09-05 15:49 UTC by ale-rt

Renames `collective.dexteritytextindexer` to `plone.textindexer`

Fixes #300
Refs. https://github.com/plone/Products.CMFPlone/issues/2780

2022-09-05 15:51 UTC, ale-rt commented
@jenkins-plone-org please run jobs

2022-09-05 15:55 UTC, ale-rt commented
Note, I started the PR jobs on jenkins manually

2022-09-07 07:11 UTC, ale-rt commented
@jenkins-plone-org please run jobs

2022-09-07 11:36 UTC, mauritsvanrees requested changes
LGTM, thanks!
But could you replace the interface as well?
`collective.dexteritytextindexer.behavior.IDexterityTextIndexer`

2022-09-07 11:38 UTC, mauritsvanrees commented
@ale-rt The Jenkins problems are [being worked on](https://github.com/plone/jenkins.plone.org/issues/290#issuecomment-1239267613).

2022-09-08 12:27 UTC, ale-rt commented
@jenkins-plone-org please run jobs

2022-09-08 22:44 UTC, mauritsvanrees approved these changes

2022-09-08 22:47 UTC, mauritsvanrees commented
Jenkins for PRs is still broken, but local tests pass, at least `bin/test -s plone.app.upgrade` and `bin/test -s Products.CMFPlone -m testMigrationTool`. I will merge. The normal Jenkins jobs after merge should work fine.

2022-09-08 22:48 UTC, merged